module.exports = {
    NO_DATA: (str) => `${str} doesn't exists!`,
    VALIDATION_NECESSARY: (str) => `${str} is required!`,
    VALIDATION_ISARRAY: (str) => `${str} must be an array!`,
    REGISTER_SUCCESS: "You have registered successfully!",
    REGISTER_FAILD: "Your registration failed. please try again!",
    LOGIN_SUCCESS: "You have logged in successfully!",
    LOGIN_FAILED: "Your logged in failed. please try again!",
    LOGOUT_SUCCESS: "You have logged out successfully!",
    LOGOUT_FAILED: "You have not logged out successfully!",
    NO_FILE: "Please, select file for upload!",
    UPLOAD_FILE_SUCCESS: "The file has been uploaded successfully!",
    DATA_EXIST: (str) => `${str} already exists!`,
    SEND_OTP_SUCCESS: (str) => `We have sent the code to your registered ${str}!`,
    SEND_OTP_FAILED: "There is some error in sending code!",
    INVALID_OTP: "Invalid Otp!",
    VERIFIED_OTP_SUCCESS: "Otp has been verified successfully!",
    UPDATE_PROFILE: (str) => `${str} has been updated successfully!`,
    UPDATE_PROFILE_FAILED: (str) => `${str} has not been updated successfully!`,
    GET_PROFILE: (str) => `${str} profile has been got successfully!`,
    CHANGE_DATA: (str) => `${str} has been changed successfully!`,
    CHANGE_DATA_FAILED: (str) => `${str} has not been changed successfully!`,
    GET_LIST: (str) => `${str} list has been got successfully!`,
    GET_DATA: (str) => `${str} data has been got successfully!`,
    ADD_DATA: (str) => `${str} data has been added successfully!`,
    ADD_DATA_FAILED: (str) => `${str} data has not been added successfully!`,
    DELETE_PROFILE: (str) => `${str} has been deleted successfully!`,
    DELETE_PROFILE_FAILED: (str) => `${str} has not been deleted successfully!`,
    APPOINTMENT_REQUEST_SENT: (str) => `${str} has been sent successfully!`,
    APPOINTMENT_REQUEST_SENT_FAILED: (str) => `${str} has not been sent successfully!`,
    APPOINTMENT_REQUEST_EXIST: (str) => `${str} already sent!`,
    NO_SUBROLE_PROFILE: (str) => `You doesn't have ${str} profile. Please register as a ${str}`,
    PHONENO_EXIST: (str) => `${str} phone no already exists!`,
    ORDER_SUCCESS: (str) => `${str} order has been placed successfully!`,
    ORDER_FAILED: (str) => `${str} order has not been placed successfully!`,
    PAYMENT_SUCCESS: (str) => `${str} payment has been done successfully!`,
    PAYMENT_FAILED: "Your payment verification failed!",
    TRANSACTION_SUCCESS: (str) => `${str} transaction has been done successfully!`,
    JOB_APPLIED: (str) => `${str} already applied in this job!`,
    APPLY_SUCCESS: (str) => `Congratulations, your ${str} application has been successfully submitted!`,
    ALREADY_APPLIED: (str) => `The ${str} has already been submitted!`,
    SUBMIT_SUCCESS: (str) => `${str} has been started successfully!`,
    SUBMIT_SUCCESS: (str) => `${str} has been started successfully!`,
    SUBMIT_FAILED: (str) => `${str} has not been started successfully!`,
    OCCUPIED: (str) => `This ${str} is currently occupied!`,
    REQUEST_SUCCESS: (str) => `${str} request has been sent successfully!`,
    REQUEST_FAILED: (str) => `${str} request has not been sent successfully!`,
    VALIDATE_COUPON: "You can use this coupon only once!",
    NO_CLINIC_OWNER: "You are not owner of clinic!",
    CLINIC_OWNER_EXIST: "You dose not add more clinic!",
    NOT_APPROVED: (str) => `please select approved ${str}!`,
    QUIZ_PENDING: (str) => `The ${str} quiz is not completed. Please complete the ${str} quiz!`,
    READ_DATA: (str) => `The ${str} has been read successfully!`,
    SOME_ERROR: `There is something went wrong!`,
    NO_FREE_REPORT: `You don't create any free oral screening report!`,
    NO_PAYPAL_SALE: `Sale not completed!`,
    NO_QUANTTY: `order quantity is out of stock!`,

}