const express = require('express')
const app = express();

module.exports = function (app) {
  require("./admin/auth.routes")(app);
  require("./admin/specialities.routes")(app);
  require("./admin/treatment.routes")(app);
  require("./admin/doctors.routes")(app);
  require("./admin/clinic_staff.routes")(app);
  require("./admin/patients.routes")(app);
  require("./admin/clinics.routes")(app);
  require("./admin/user.routes")(app);
  require("./admin/subadmin.routes")(app);
  require("./admin/degree.routes")(app);
  require("./admin/collage.routes")(app);
  require("./admin/cities.routes")(app);
  require("./admin/areas.routes")(app);
  require("./admin/facilities.routes")(app);
  require("./admin/symptoms.routes")(app);
  require("./admin/health_assessments.routes")(app);
  require("./admin/health_assessment_quiz.routes")(app);
  require("./admin/promocods.routes")(app);
  require("./admin/topics.routes")(app);
  require("./admin/pharmacies.routes")(app);
  require("./admin/blogs.routes")(app);
  require("./admin/ecom_product_categories.routes")(app);
  require("./admin/ecom_products.routes")(app);
  require("./admin/appointments.routes")(app);
  require("./admin/challenges.routes")(app);
  require("./admin/oral_screening_quiz.routes")(app);
  require("./admin/diseases.routes")(app);
  require("./admin/static_pages.routes")(app);
  require("./admin/transactions.routes")(app);
  require("./admin/push_notification.routes")(app);
  require("./admin/withdraw_request.routes")(app);
  require("./admin/oral_screening_reports.routes.js")(app);
  require("./admin/settings.routes.js")(app);
  require("./admin/notice_board.routes")(app)
  require("./admin/ticket.routes")(app);
  require("./admin/oral_doctors.routes.js")(app)
  require("./admin/health_assessment_report.routes.js")(app)
  require("./admin/medicines.routes.js")(app)
  require("./admin/insurance_companies.routes.js")(app)
  require("./admin/registration_councils.routes.js")(app)
  require("./admin/lab_tests.routes.js")(app)
  require("./admin/banners.routes.js")(app)
  require("./admin/subscription.routes.js")(app)
  require("./admin/cancer_assistances.routes.js")(app)
  require("./admin/financial_dashboard.routes.js")(app)

  require("./oral_doctor/auth.routes.js")(app)
  require("./oral_doctor/oral_screening_reports.routes.js")(app)

  require("./enduser/auth.routes")(app)
  require("./enduser/patient/familyMember.routes")(app)
  require("./enduser/patient/consultation.routes")(app)
  require("./enduser/patient/dashboard.routes")(app)
  require("./enduser/patient/healthAssessment.routes")(app)
  require("./enduser/patient/ecomProduct.routes")(app)
  require("./enduser/patient/blog.routes")(app)
  require("./enduser/patient/cancer_assistance.routes")(app)
  require("./enduser/staticPages.routes")(app)
  require("./enduser/patient/challenge.routes")(app)
  require("./enduser/patient/healthTracker.routes")(app)
  require("./enduser/patient/ambulance.routes")(app)
  require("./enduser/patient/facial_asthetic.routes")(app)
  require("./enduser/patient/help_center.routes")(app)
  require("./enduser/patient/AIScreening.routes")(app)
  require("./enduser/patient/home_visit.routes")(app)
  require("./enduser/patient/ticket.routes")(app)
  require("./enduser/patient/notification.routes.js")(app)
  require("./enduser/patient/jitsi_consultation.routes.js")(app)
  require("./enduser/patient/labtest.routes.js")(app)
  require("./enduser/patient/financial_dashboard.routes.js")(app)

  require("./enduser/doctor/profile.routes")(app)
  require("./enduser/doctor/dashboard.routes")(app);
  require("./enduser/doctor/financial_dashboard.routes")(app);
  require("./enduser/doctor/ecomProduct.routes")(app)
  require("./enduser/doctor/job.routes")(app)
  require("./enduser/doctor/patient_request.routes")(app)
  require("./enduser/doctor/research_post.routes")(app)
  require("./enduser/doctor/co_working_space.routes")(app)
  require("./enduser/doctor/hr_management.routes.js")(app)
  require("./enduser/doctor/treatment.routes.js")(app)
  require("./enduser/doctor/notice_board.routes.js")(app)
  require("./enduser/doctor/subscription.routes.js")(app)
  require("./enduser/doctor/notification.routes.js")(app)
  require("./enduser/doctor/help_center.routes.js")(app)

  require("./enduser/clinic/profile.routes")(app)
  require("./enduser/clinic/raised_ticket.routes")(app)
  require("./enduser/clinic/dashboard.routes")(app)
  require("./enduser/clinic/appointment.routes")(app)
  require("./enduser/clinic/patient.routes.js")(app)
  require("./enduser/clinic/hr_management.routes.js")(app)
  require("./enduser/clinic/treatment.routes.js")(app)
  require("./enduser/clinic/bloodbank.routes.js")(app)
  require("./enduser/clinic/job.routes.js")(app)
  require("./enduser/clinic/financial_dashboard.routes")(app)
  require("./enduser/clinic/inventory_management.routes")(app)
  require("./enduser/clinic/pharmacy.routes.js")(app)
  require("./enduser/clinic/ambulance.routes.js")(app)
  require("./enduser/clinic/co_working_space.routes.js")(app)
  require("./enduser/clinic/health_camp.routes")(app)
  require("./enduser/clinic/banners.routes")(app)
  require("./enduser/clinic/ecomProduct.routes")(app)
  require("./enduser/clinic/sos.routes")(app)
  require("./enduser/clinic/blogs.routes")(app)
  require("./enduser/clinic/notice_board.routes")(app)
  require("./enduser/clinic/beds.routes")(app)
  require("./enduser/clinic/lab_tests.routes.js")(app)
  require("./enduser/clinic/help_center.routes.js")(app)
}
